{% set name = "Flask-SocketIO" %}
{% set version = "4.2.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2172dff1e42415ba480cee02c30c2fc833671ff326f1598ee3d69aa02cf768ec" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - flask >=0.9
    - python-socketio >=2.1.0,<4

test:
  imports:
    - flask_socketio
    - flask_socketio.namespace
    - flask_socketio.test_client

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Socket.IO integration for Flask applications'
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/

extra:
  recipe-maintainers:
    - pmlandwehr
