{% set name = "Flask-SocketIO" %}
{% set version = "5.0.1" %}
{% set bundle = "tar.gz" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: 5c4319f5214ada20807857dc8fdf3dc7d2afe8d6dd38f5c516c72e2be47d2227

build:
  noarch: python
  preserve_egg_dir: true
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - flask >=0.9
    - python-socketio >=5.0.2

test:
  imports:
    - flask_socketio
    - flask_socketio.namespace
    - flask_socketio.test_client

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Socket.IO integration for Flask applications
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
