{% set name = "Flask-SocketIO" %}
{% set version = "5.0.2" %}
{% set bundle = "tar.gz" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: 34f27dccbf4e8efd739571d6166f96e44f8fe3bbc560b99c7d7f53aaaa40649c

build:
  noarch: python
  preserve_egg_dir: true
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - flask >=0.9
    - python-socketio >=5.0.2

test:
  imports:
    - flask_socketio
    - flask_socketio.namespace
    - flask_socketio.test_client

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Socket.IO integration for Flask applications
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
