context:
  version: "5.6.0"
  python_min: "3.9"

package:
  name: flask-socketio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-socketio/flask_socketio-${{ version }}.tar.gz
  sha256: 42a7bc552013633875ad320e39462323b4f7334594f1658d72b6ffed99940d4c

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.2
  run:
    - python >=${{ python_min }}
    - flask >=2.1.0
    - python-socketio >=5.12.0

tests:
  - python:
      imports:
        - flask_socketio
        - flask_socketio.namespace
        - flask_socketio.test_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Socket.IO integration for Flask applications
  homepage: https://github.com/miguelgrinberg/Flask-SocketIO/
  repository: https://github.com/miguelgrinberg/Flask-SocketIO/
  documentation: https://flask-socketio.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
    - jan-janssen
