context:
  version: 5.5.1
  python_min: "3.9"

package:
  name: flask-socketio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-socketio/flask_socketio-${{ version }}.tar.gz
  sha256: d946c944a1074ccad8e99485a6f5c79bc5789e3ea4df0bb9c864939586c51ec4

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >=${{ python_min }}
    - flask >=0.9
    - python-socketio >=5.12.0

tests:
  - python:
      imports:
        - flask_socketio
        - flask_socketio.namespace
        - flask_socketio.test_client
  - script:
      - python -c "import flask_socketio"
    requirements:
      run:
        - python =${{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  summary: Socket.IO integration for Flask applications
  homepage: https://github.com/miguelgrinberg/Flask-SocketIO/
  repository: https://github.com/miguelgrinberg/Flask-SocketIO/
  documentation: https://flask-socketio.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
    - jan-janssen
