travis:
  secure:
    BINSTAR_TOKEN: aJ+xJXLgOCfwNa+MQzpKgBMPe6rz4hiG8xaCrMGcfUpygeYN57YyjF2YNXOWLRYhEimF87zJkcVcb+GBpSkpqMtZ3zcSYarY9OiNBmF3IOx8M+oX2THtnvZQ/gSrT5lxlPwJn8hTu0dGQmV2CKmGbcKXJFvlWN60jfOjYp4aF1qJgEIkw1q05AuHUITX8pdA931PUxECZlDXlBeLt82JhqotdlXRyqkSwLdMJ17HfzcoPcYDmeUaz5F/8KtPHIfDl64+efPeP+HiH3gMmd1BtCTVEM4jw0ybYqLx37FR7OqJ8cacG+rF84/WKNzwJJLq02M8tCeoVWeOmb+hD6/slwmAoGNUg5Mj0yzfJ6S3BHbxpIvf07e87+UUSCGxAOTDjvWS6/VHDpfajgFwz+luHwAj0+uIlPkdSpCd7nRI9d+jEOFl2tncTOQ01LWWk2mNTviHu4NG4DgkwRDzFNZ2w459BvSKTwnw5gwYc+1eVoAUErsToQFp2zGM+aOkJdnl9FZiqMvfrwqJyUy5uL33WY8iAFF2uvFpKlRz56q01nFPcj3YogYqPpAKgGRzqo/QWjMHtxk1OrdnWWfz+a3OKzrdCK8SVf8Vvuc0BwL1TPYghSCwWK4eiXzIj/R7cVLuQqmr5wcyErjzocihJBQMxxiOV+MCrIdJaXOstqd67Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
